export const DropDownNum = [
  { value: '1', label: '1' },
  { value: '2', label: '2' },
  { value: '3', label: '3' },
  { value: '4', label: '4' },
  { value: '5', label: '5' },
  { value: '6', label: '6' },
  { value: '7', label: '7' },
  { value: '8', label: '8' },
  { value: '9', label: '9' },
  { value: '10', label: '10' },
  { value: '11', label: '11' },
  { value: '12', label: '12' },
  { value: '13', label: '13' },
  { value: '14', label: '14' },
  { value: '15', label: '15' }
]

export const DropDownTime = [
  { value: 'AM 9:00', label: 'AM 9:00' },
  { value: 'AM 9:30', label: 'AM 9:30' },
  { value: 'AM 10:00', label: 'AM 10:00' },
  { value: 'AM 10:30', label: 'AM 10:30' },
  { value: 'AM 11:00', label: 'AM 11:00' },
  { value: 'AM 11:30', label: 'AM 11:30' },
  { value: 'PM 12:00', label: 'PM 12:00' },
  { value: 'PM 12:30', label: 'PM 12:30' },
  { value: 'PM 1:00', label: 'PM 1:00' },
  { value: 'PM 1:30', label: 'PM 1:30' },
  { value: 'PM 2:00', label: 'PM 2:00' },
  { value: 'PM 2:30', label: 'PM 2:30' },
  { value: 'PM 3:00', label: 'PM 3:00' },
  { value: 'PM 3:30', label: 'PM 3:30' },
  { value: 'PM 4:00', label: 'PM 4:00' },
  { value: 'PM 4:30', label: 'PM 4:30' },
  { value: 'PM 5:00', label: 'PM 5:00' },
  { value: 'PM 5:30', label: 'PM 5:30' },
  { value: 'PM 6:00', label: 'PM 6:00' },
  { value: 'PM 6:30', label: 'PM 6:30' },
  { value: 'PM 7:00', label: 'PM 7:00' },
  { value: 'PM 7:30', label: 'PM 7:30' },
]

export const DropDowncharger = [
  { value: '조동희', label: '조동희' },
  { value: '김철수', label: '김철수' },
  { value: '조수환', label: '조수환' },
  { value: '김수진', label: '김수진' },
  { value: '류주희', label: '류주희' },
  { value: '박정준', label: '박정준' },
  { value: '박지혜', label: '박지혜' },
  { value: '이한나', label: '이한나' },
]

export const DropDownVisitPath = [
  { value: '웹사이트', label: '웹사이트' },
  { value: '박람회페이지', label: '박람회페이지' },
  { value: '업체소개', label: '업체소개' },
  { value: '전화상담', label: '전화상담' },
  { value: '카톡상담', label: '카톡상담' },
  { value: '방문상담', label: '방문상담' },
  { value: '지인소개', label: '지인소개' },
  { value: '사원지인', label: '사원지인' }
]

export const DropDownTourLocation = [
  { value: '코사무이', label: '코사무이' },
  { value: '푸켓', label: '푸켓' },
  { value: '카오락', label: '카오락' },
  { value: '크라비', label: '크라비' },
  { value: '다낭', label: '다낭' },
  { value: '나트랑', label: '나트랑' },
  { value: '푸꾸옥', label: '푸꾸옥' },
  { value: '세부', label: '세부' },
  { value: '보라카이', label: '보라카이' },
  { value: '괌', label: '괌' },
  { value: '뉴질랜드', label: '뉴질랜드' },
  { value: '동유럽', label: '동유럽' },
  { value: '두바이', label: '두바이' },
  { value: '랑카위', label: '랑카위' },
  { value: '모두투어', label: '모두투어' },
  { value: '모리셔스', label: '모리셔스' },
  { value: '몰디브', label: '몰디브' },
  { value: '미본토', label: '미본토' },
  { value: '발리', label: '발리' },
  { value: '베트남', label: '베트남' },
  { value: '사이판', label: '사이판' },
  { value: '서유럽', label: '서유럽' },
  { value: '세이쉘', label: '세이쉘' },
  { value: '스페인', label: '스페인' },
  { value: '싱가폴', label: '싱가폴' },
  { value: '유럽', label: '유럽' },
  { value: '일본', label: '일본' },
  { value: '제주도', label: '제주도' },
  { value: '중국(하이난)', label: '중국(하이난)' },
  { value: '중남미', label: '중남미' },
  { value: '지중해', label: '지중해' },
  { value: '칸쿤', label: '칸쿤' },
  { value: '캐나다', label: '캐나다' },
  { value: '코타키나바루', label: '코타키나바루' },
  { value: '타히티', label: '타히티' },
  { value: '태국', label: '태국' },
  { value: '필리핀', label: '필리핀' },
  { value: '하나투어', label: '하나투어' },
  { value: '하와이', label: '하와이' },
  { value: '호주', label: '호주' },
  { value: '홍콩', label: '홍콩' },
  { value: '기타', label: '기타' }
]

export const DropDownAirline = [
  { value: '5J', label: '5J 세부퍼시픽 항공' },
  { value: '5M', label: '5M 메가몰디브' },
  { value: '7C', label: '7C 제주항공' },
  { value: '8B', label: '8B 비지니스에어' },
  { value: 'AA', label: 'AA 아메리칸항공' },
  { value: 'AM', label: 'AM 아에로멕시코항공' },
  { value: 'BX', label: 'BX 부산에어' },
  { value: 'CX', label: 'CX 캐세이퍼시픽 항공' },
  { value: 'D7', label: 'D7 에어아시아' },
  { value: 'EK', label: 'EK 에미레이트 항공' },
  { value: 'EY', label: 'EY 에티하드 항공' },
  { value: 'GA', label: 'GA 가루다 항공' },
  { value: 'HA', label: 'HA 하와이안 항공' },
  { value: 'JL', label: 'JL 일본 항공' },
  { value: 'JQ', label: 'JQ 젯스타항공' },
  { value: 'KE', label: 'KE 대한항공' },
  { value: 'LJ', label: 'LJ 진에어 항공' },
  { value: 'MH', label: 'MH 말레이시아 항공' },
  { value: 'OZ', label: 'OZ 아시아나' },
  { value: 'PG', label: 'PG 방콕 항공' },
  { value: 'PR', label: 'PR 필리핀' },
  { value: 'QF', label: 'QF 콴타스호주 항공' },
  { value: 'QR', label: 'QR 카타르 항공' },
  { value: 'SQ', label: 'SQ 싱가폴 항공' },
  { value: 'TG', label: 'TG 타이항공' },
  { value: 'TK', label: 'TK 터키항공' },
  { value: 'TN', label: 'TN 타히티 누이 항공' },
  { value: 'TW', label: 'TW 티웨이항공' },
  { value: 'UA', label: 'UA 유나이티드 항공' },
  { value: 'VJ', label: 'VJ 비엣젯항공' },
  { value: 'VN', label: 'VN 베트남항공' },
  { value: 'ZA', label: 'ZA 제스트항공' },
  { value: 'ZE', label: 'ZE 이스타 항공' }
]

export const DropDownLandCompany = [
  { value: "선택", label: "선택" },
  { value: "007", label: "007" },
  { value: "A.U.M", label: "A.U.M" },
  { value: "FT타이", label: "FT타이" },
  { value: "GRM", label: "GRM" },
  { value: "H투어", label: "H투어" },
  { value: "IMT", label: "IMT" },
  { value: "KTB", label: "KTB" },
  { value: "K투어", label: "K투어" },
  { value: "K투어동남아", label: "K투어동남아" },
  { value: "LTB", label: "LTB" },
  { value: "MMD", label: "MMD" },
  { value: "SJ 몰디브", label: "SJ 몰디브" },
  { value: "SP 몰디브", label: "SP 몰디브" },
  { value: "SS투어", label: "SS투어" },
  { value: "TFK", label: "TFK" },
  { value: "TS트래블", label: "TS트래블" },
  { value: "VIP항공", label: "VIP항공" },
  { value: "가자하와이", label: "가자하와이" },
  { value: "고객직접 발권", label: "고객직접 발권" },
  { value: "고려투어몰", label: "고려투어몰" },
  { value: "고몰디브", label: "고몰디브" },
  { value: "골든홀리데이", label: "골든홀리데이" },
  { value: "굿초이스투어", label: "굿초이스투어" },
  { value: "네오코리아", label: "네오코리아" },
  { value: "노랑풍선", label: "노랑풍선" },
  { value: "다이나믹 괌", label: "다이나믹 괌" },
  { value: "다이나믹투어", label: "다이나믹투어" },
  { value: "대아투어", label: "대아투어" },
  { value: "대한항공", label: "대한항공" },
  { value: "더랜드", label: "더랜드" },
  { value: "델피노투어", label: "델피노투어" },
  { value: "두리두바이", label: "두리두바이" },
  { value: "드림링스", label: "드림링스" },
  { value: "드림티앤이", label: "드림티앤이" },
  { value: "랜드로그인", label: "랜드로그인" },
  { value: "랜드아이콘", label: "랜드아이콘" },
  { value: "렛츠", label: "렛츠" },
  { value: "리조트마케팅", label: "리조트마케팅" },
  { value: "마이리얼트립", label: "마이리얼트립" },
  { value: "모두투어", label: "모두투어" },
  { value: "몰디브넷", label: "몰디브넷" },
  { value: "바캉스", label: "바캉스" },
  { value: "빅프라임투어", label: "빅프라임투어" },
  { value: "스핀", label: "스핀" },
  { value: "스핀투어", label: "스핀투어" },
  { value: "써니", label: "써니" },
  { value: "어바웃유럽", label: "어바웃유럽" },
  { value: "에어부산", label: "에어부산" },
  { value: "여행을찾다", label: "여행을찾다" },
  { value: "여행이지", label: "여행이지" },
  { value: "예스", label: "예스" },
  { value: "예스투어", label: "예스투어" },
  { value: "오리엔탈", label: "오리엔탈" },
  { value: "온라인투어", label: "온라인투어" },
  { value: "와이페이모어", label: "와이페이모어" },
  { value: "요금미정", label: "요금미정" },
  { value: "울트라재팬", label: "울트라재팬" },
  { value: "원더풀투어", label: "원더풀투어" },
  { value: "웹투어", label: "웹투어" },
  { value: "유나이티드에이젼시(항공)", label: "유나이티드에이젼시(항공)" },
  { value: "유로자전거나라", label: "유로자전거나라" },
  { value: "유앤미", label: "유앤미" },
  { value: "이투아리스", label: "이투아리스" },
  { value: "인터파크", label: "인터파크" },
  { value: "제주OK렌트카", label: "제주OK렌트카" },
  { value: "제주항공", label: "제주항공" },
  { value: "젠몰디브", label: "젠몰디브" },
  { value: "진에어", label: "진에어" },
  { value: "참좋은여행", label: "참좋은여행" },
  { value: "창투어", label: "창투어" },
  { value: "최윤경-토파스", label: "최윤경-토파스" },
  { value: "최윤경-토파스발권", label: "최윤경-토파스발권" },
  { value: "카바나", label: "카바나" },
  { value: "콩코드", label: "콩코드" },
  { value: "타이항공", label: "타이항공" },
  { value: "탑투어", label: "탑투어" },
  { value: "토성항공", label: "토성항공" },
  { value: "투어티라", label: "투어티라" },
  { value: "트래벌비즈", label: "트래벌비즈" },
  { value: "티웨이", label: "티웨이" },
  { value: "파크우드", label: "파크우드" },
  { value: "팍스투어", label: "팍스투어" },
  { value: "퍼시픽", label: "퍼시픽" },
  { value: "퍼시픽유럽", label: "퍼시픽유럽" },
  { value: "퍼플 동남아", label: "퍼플 동남아" },
  { value: "퍼플하오이 동남아", label: "퍼플하오이 동남아" },
  { value: "퍼플하와이", label: "퍼플하와이" },
  { value: "프라이데이", label: "프라이데이" },
  { value: "하나몰디브", label: "하나몰디브" },
  { value: "하나투어", label: "하나투어" },
  { value: "하이투어", label: "하이투어" },
  { value: "허니문마케팅", label: "허니문마케팅" },
  { value: "호텔패스", label: "호텔패스" }
]

export const DropDownDepositType = [
  { value: '현금', label: '현금' },
  { value: '무통장입금', label: '무통장입금' },
  { value: '신용카드', label: '신용카드' },
  { value: '카드+입금', label: '카드+입금' },
  { value: '수표입금', label: '수표입금' }
]

export const DropDownDeliveryType = [
  { value: '카톡', label: '카톡' },
  { value: '전화', label: '전화' }
]


